#!/bin/zsh
mkdir $1 && cd $1
git clone git@github.com:andykmiles/py.git .
mkdir -p src/$1
mkdir tests
mkdir docs
mv {{proj}}.Dockerfile $1.Dockerfile
git remote rm origin

sed -i "s/{{proj}}/$1/g" setup.py
sed -i "s/{{proj}}/$1/g" pytest
sed -i "s/{{proj}}/$1/g" python
sed -i "s/{{proj}}/$1/g" terminal
sed -i "s/{{proj}}/$1/g" build-dev

./build-dev
git add . && git commit -m "init"
gh repo create $1 --public -y
git push origin master
